### ISSUE TITLE
[Q]What it the version of nginx?

### ISSUE THREAD

**Issue by vikashconnect** [graphite-project/docker-graphite-statsd#183]
**Please ask questions only for Docker component here, if you want to do so about Graphite, please use [graphite-web repo](https://github.com/graphite-project/graphite-web/issues/new/choose)**

**Comment by vikashconnect** [comment]
nginx 0.6.x < 1.20.1 1-Byte Memory Overwrite RCE

Any one can help me to upgrade nginx to latest version

**Comment by deniszh** [comment]
Hi @vikashconnect 

No need to upgrade Nginx. According to https://gitlab.alpinelinux.org/alpine/aports/-/commit/ca087996b58a77a9e3c1aaee70ad8645a7caa612 issue was fixed in Nginx 1.16.1-rc3 7 month ago. 
1.1.8-2 was built 3 months ago and already contains that fix.

**Comment by vikashconnect** [comment]
> Hi @vikashconnect
> 
> No need to upgrade Nginx. According to https://gitlab.alpinelinux.org/alpine/aports/-/commit/ca087996b58a77a9e3c1aaee70ad8645a7caa612 issue was fixed in Nginx 1.16.1-r3 7 months ago. Image was built 3 months ago and already contains that fix.

Thanks:)

**Comment by vikashconnect** [comment]
HI @deniszh 
Requesting you to please go through  below link, as per this needs to upgrade nginx
http://mailman.nginx.org/pipermail/nginx-announce/2021/000300.html

**Comment by deniszh** [comment]
Hi @vikashconnect 

Yes, that post mentioning  CVE-2021-23017 which was fixed by Alpine linux mainainers in Nginx 1.16.1-r3 7 months ago, as my previous link said. 
No need to upgrade Nginx to latest version, it can be potentially non- compatible with existing configurations, that's why usually you're use Nginx and other software from your Linux distribution and trust its maintainers for apply security patches. But for issue above it's not blind trust - it's open source, so, you can see that fix is indeed applied.
If your security scanner still complains about it - well, that means your security scanner just can't detect fix and complains solely about versiin number, which is wrong. You can make Nginx to stop showing its version then.
