### ISSUE TITLE
Django Admin password

### ISSUE THREAD

**Issue by kotireddy478** [graphite-project/docker-graphite-statsd#199]
Is it possible to change defult Django Admin password via commandline?
I'm trying to update the password via Ansible.

**Comment by deniszh** [comment]
If you use this docker image you need to run command `/opt/graphite/bin/python3 /opt/graphite/bin/django-admin.py changepassword` inside running container. Not sure if Ansible can do that, otherwise I would recommentd to insert  new password in https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/bin/django_admin_init.sh#L12 and rebuild image

**Comment by kotireddy478** [comment]
Hi,

Thanks for you input on this. I have tried to run the command but getting below error.

```
 /opt/graphite/bin/python3 /opt/graphite/bin/django-admin.py changepassword
No Django settings specified.
Unknown command: 'changepassword'
Type 'django-admin.py help' for usage.

```

**Comment by deniszh** [comment]
hi @kotireddy478 

Should be easy to implement in https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/bin/django_admin_init.sh . Get env variable if exists, otherwise default and apply it in https://github.com/graphite-project/docker-graphite-statsd/blob/master/conf/opt/graphite/bin/django_admin_init.sh#L12

**Comment by kotireddy478** [comment]
Thank you so much for your help.
